    FieldFoo(<u32 as ::configure_me::parse_arg::ParseArg>::Error),
    FieldBar(<String as ::configure_me::parse_arg::ParseArg>::Error),
    FieldBaz(<String as ::configure_me::parse_arg::ParseArg>::Error),
    FieldVerbose(::std::ffi::OsString),
    FieldFast(::std::ffi::OsString),
