[package]
name = "configure_me_codegen"
version = "0.3.0"
authors = ["Martin Habovštiak <martin.habovstiak@gmail.com>"]
description = "A library for processing application configuration easily."
homepage = "https://github.com/Kixunil/configure_me"
repository = "https://github.com/Kixunil/configure_me"
readme = "README.md"
keywords = ["configuration", "arguments", "environment", "codegen"]
categories = ["command-line-interface", "config", "encoding"]
license = "MITNFA"
maintenance = { status = "actively-maintained" }
build = "build.rs"

[features]
default = ["man"]

[dependencies]
serde = "1"
serde_derive = "1"
toml = "0.4.8"
unicode-segmentation = "1.2"
fmt2io = "0.1"
build-helper = "0.1.1"
man = { version = "0.1.1", optional = true }

[dev-dependencies]
pretty_assertions = "0.5.1"
configure_me = "0.3.0"
